### ISSUE TITLE
DEVICE NOT CONNECTED!

### ISSUE THREAD

**Issue by kksuthar321** [WeatherFlow/WindMeterSDK#5]
My windmeter device is connected with iphone through audio jack. But still getting decvice not connectecd.

Device is succesfully conected in wind meter app via blutooth. but not connecting with audio jack. 
Please any one can explain that how to fully intergate wind meter to my own app with blutooth and audio jack.

**Comment by dstjohn** [comment]
Hi there. The WINDmeter  uses the audio jack, not Bluetooth. There is a separate SDK for the WEATHERmeter (which uses bluetooth), but that is not public yet. We'd be happy to share the WEATHERmeter SDK with you - just tell me a little more about your app by emailing me directly: dstjohn@weatherflow.com
