### ISSUE TITLE
SDK for iOS

### ISSUE THREAD

**Issue by IgorBorisov** [WeatherFlow/WindMeterSDK#7]
Where can I find missing files:
AnemometerInterface.h
DeviceLocation.h
I cannot compile my project without them
Igor Borisov

**Comment by dtrauger** [comment]
Sounds like you might not have the project configured properly.  There is an included example project (https://github.com/WeatherFlow/WindMeterSDK/tree/master/iOS/Full%20Integration%20Example) available as well as some basic configuration instructions (https://github.com/WeatherFlow/WindMeterSDK/tree/master/iOS/Full%20Integration%20Example).  Take a look at the "Project Setup" instructions it sounds like you may not have dragged the "WindMeterSDK" folder into the project or the linker flags might not have been added.  In either event the "Project Setup" instructions is where I would start.  If you continue to run into problems, please let me know.

**Comment by IgorBorisov** [comment]
Look here, please: https://github.com/WeatherFlow/WindMeterSDK/blob/master/iOS/Full%20Integration%20Example/WindMeterSDK/WindMeterSDKHeaders/WindMeterSDK.h
You can see in this file: 

#import <Foundation/Foundation.h>
#import <AVFoundation/AVFoundation.h>
#import <AudioUnit/AudioUnit.h>
#import <AudioToolbox/AudioToolbox.h>
#import <MediaPlayer/MediaPlayer.h>
#import <CoreLocation/CoreLocation.h>
#import "AnemometerInterface.h"
#import "AnemometerObservation.h"
#import "SensorStatus.h"
#import “DeviceLocation.h"

My XCode can not find files AnemometerInterface.h and DeviceLocation.h

Igor Borisov

**Comment by dtrauger** [comment]
Igor,

Please download the sample project, I just tested it and all appears to compile as expected.  Please make sure the linker flags are set as directed in the setup instructions.

Do you run into the same issue when attempting to compile the sample project?

Derek

**Comment by IgorBorisov** [comment]
I have old version SDK installed and my project was compiled fine. I try to download latest version of SDK and new version can not be compiled due two header files missing

Igor Borisov

**Comment by dtrauger** [comment]
The sample project in question leverages the latest version of the SDK.
Are you able to compile the sample project?

**Comment by IgorBorisov** [comment]
Yes. But sample project contents another header file WindMeterSDK.h. Here is  content:

//
//  WindMeterSDK.h
//  WindMeterSDK
//
//  Created by Derek Trauger on 6/26/14.
//  Copyright (c) 2014 WeatherFlow. All rights reserved.
//

#import "AnemometerObservation.h"
#import "SensorStatus.h"

@interface WindMeterSDK : NSObject {
    AnemometerObservation *anemometerOb;
    void (^_valueChangedHandler)(AnemometerObservation *value);
}

- (id)init;
- (void)startListener;
- (void)stopListener;
- (void)reportValueChange:(void(^)(AnemometerObservation *))handler;
- (void)destroySensor;

@end


But here https://github.com/WeatherFlow/WindMeterSDK/blob/master/iOS/Full%20Integration%20Example/WindMeterSDK/WindMeterSDKHeaders/WindMeterSDK.h <https://github.com/WeatherFlow/WindMeterSDK/blob/master/iOS/Full%20Integration%20Example/WindMeterSDK/WindMeterSDKHeaders/WindMeterSDK.h>
we have another header file with content:

//
// WindMeterSDK.h
// WindMeterSDK
//
// Created by Derek Trauger on 6/26/14.
// Copyright (c) 2014 WeatherFlow. All rights reserved.
//
#import <Foundation/Foundation.h>
#import <AVFoundation/AVFoundation.h>
#import <AudioUnit/AudioUnit.h>
#import <AudioToolbox/AudioToolbox.h>
#import <MediaPlayer/MediaPlayer.h>
#import <CoreLocation/CoreLocation.h>
#import "AnemometerInterface.h"
#import "AnemometerObservation.h"
#import "SensorStatus.h"
#import "DeviceLocation.h"
#define VOLUME_SETTING_KEY @"wf_sensor_volume_key"
@interface WindMeterSDK : NSObject <CLLocationManagerDelegate> {
AVAudioPlayer *audioPlayer;
AVAudioRecorder *audioRecorder;
BOOL isListening;
BOOL capturedAudio;
float currentRPM;
AnemometerInterface *anemometerRef;
AnemometerObservation *anemometerOb;
DeviceLocation *deviceLocation;
void (^_valueChangedHandler)(AnemometerObservation *value);
MPMusicPlayerController *audioPlayerController;
CLLocationManager *locationManager;
NSTimer *timer1;
}
@property (nonatomic, assign) AnemometerInterface *anemometerRef;
@property (assign) BOOL isListening;
- (id)init;
- (void)startListener;
- (void)stopListener;
- (void)openClosedChangedWithValue:(float)newValue;
- (void) reportValueChange:(void(^)(AnemometerObservation *))handler;
- (void)destroySensor;
@end


Why?

Igor Borisov

**Comment by dtrauger** [comment]
Igor,

The headers were out of sync.  The headers used in the example project are the latest.  The headers outside of the example project has been synchronized.  https://github.com/WeatherFlow/WindMeterSDK/tree/master/iOS/Full%20Integration%20Example/WindMeterSDK

Derek

**Comment by IgorBorisov** [comment]
OK
Igor Borisov

**Comment by IgorBorisov** [comment]
Also I have problem with Android version. Some users with Samsung Note 4 with Android 5 can not get WINDMeter worked. I can not find the reason because I can not see what is happens inside SDK library. Any thoughts? I have few reports and all of them from users with Samsung Note 4. Very strange.

Igor Borisov
